Fix parameter override not working for lists of strings in Python 3.7 (#39)
Summary:
```
$ python3.6
>>> from typing import List
>>> isinstance(List[str], type)
True
>>> issubclass(List[str], list)
True
```
```
$ python3.7
>>> from typing import List
>>> isinstance(List[str], type)
False
>>> issubclass(List[str], list)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 1 must be a class
```

Fixes #38.

- [ ] Docs change / refactoring / dependency upgrade
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

See #38.

Ran the `torchbiggraph_train` command reported in #38 under both Python 3.6 and 3.7.
Pull Request resolved: https://github.com/facebookresearch/PyTorch-BigGraph/pull/39

Differential Revision: D15063827

Pulled By: lerks

fbshipit-source-id: 44fd07a19174fc0957c608e20e381635ca971d99