Tmarkovich/fixup (#229)
Summary:
## Types of changes

This is a minor bug fix to fix some issues that I ran into when feeding weights into BigGraph during experimentation.

- [X] Bug fix (non-breaking change which fixes an issue)

## Motivation and Context / Related issue

This change was required because both using the TSVEdgelistReader threw errors using the latest commit, and because supplying a weights column would throw errors as well. Those errors shouldn't show up any more.

## How Has This Been Tested (if it applies)

I've run this against real-world training payloads and training completes without issue.

## Checklist

- [X] The documentation is up-to-date with the changes I made.
- [X] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

2 tests failed on both master and this new branch. Namely:

```
======================================================================
FAIL: test_basic (test.test_batching.TestBatchEdgesGroupByType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/thomasmarkovich/Documents/PyTorch-BigGraph/test/test_batching.py", line 173, in test_basic
    self.assertEqual(
AssertionError: {0: E[30 chars] 13, 38, 77]), TensorList(tensor([0, 0, 0, 0, [612 chars]one)} != {0: E[30 chars] 13, 77, 38]), TensorList(tensor([0, 0, 0, 0, [612 chars]one)}
Diff is 1811 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_basic (test.test_batching.TestGroupByRelationType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/thomasmarkovich/Documents/PyTorch-BigGraph/test/test_batching.py", line 24, in test_basic
    self.assertEqual(
AssertionError: Lists differ: [Edge[27 chars] 13, 38, 77]), TensorList(tensor([0, 0, 0, 0, [606 chars]one)] != [Edge[27 chars] 13, 77, 38]), TensorList(tensor([0, 0, 0, 0, [606 chars]one)]

First differing element 0:
EdgeL[26 chars] 13, 38, 77]), TensorList(tensor([0, 0, 0, 0, [155 chars]None)
EdgeL[26 chars] 13, 77, 38]), TensorList(tensor([0, 0, 0, 0, [155 chars]None)

Diff is 1784 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
```

I can fix these tests, but I would need to look further into where the errors are coming from.

Finally, on an entirely off topic note, do you all need help getting weight support on the GPU?

Pull Request resolved: https://github.com/facebookresearch/PyTorch-BigGraph/pull/229

Reviewed By: lw

Differential Revision: D30220832

Pulled By: adamlerer

fbshipit-source-id: bc755d50f585d02ac0723572b07afdc1f86c9b3c